### ISSUE TITLE
Warning in taShrink

### ISSUE THREAD

**Issue by catavallejos** [HGray384/TAS#1]
Hi Harry,

Here are two suggested fixes for the `taShrink` function:

- The following warning arises when the `targets` argument is set to be an array of target matrices:

```
Warning message:
In if (targets == "default") { :
  the condition has length > 1 and only the first element will be used
```
As a solution, I suggest to replace the conditional statement `if(targets == "default")` as follows:

```
if( (length(targets) == 1) & (targets == "default") )
```

- The documentation of `taShrink` does not include an example in which the `targets` argument is used. I suggest to include one. 

Thanks!

Cata

**Comment by HGray384** [comment]
Hi Cata,

I think you might be using an old version of the code. That control flow was replaced in the last commit as per Gwen's suggestions. 

Can you reinstall and see if you get the same warning please? If so, can you give me the line number for the code that causes it.

In any case, the examples still don't currently include a specified array of targets so I'll amend that soon.

Thanks!

**Comment by catavallejos** [comment]
Thanks Harry. I've just updated the library.

Could you please confirm whether the input matrix for `taShrink` is $n \times p$ or $p \times n$?

Also, I'd suggest to remove the following warning:

```
TAS was designed for high-dimensional data analysis, but the 
            number of variables (p) in your X is less than the number 
            of samples (n). 
 
            If you know that this warning is incorrect then likely you need to 
            transpose X and run TAS again. Otherwise, know that
            TAS might not be the most suitable method here. 
```

As shrinkage methods might also be helpful in situations in which $n$ is larger than $p$, but not much larger.

**Comment by catavallejos** [comment]
Also, could you please check if there is any issue with the help files?

I am unable to access the documentation after loading the latest version of the library. The following message appears: 

```
Error in fetch(key) : lazy-load database '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/TAS/help/TAS.rdb' is corrupt
```

**Comment by HGray384** [comment]
The input matrix is (p x n) and I will amend the warning message.

I've just rebuilt the documentation and pushed the changes - hopefully this will fix your problem. Could you try and reinstall again please? Sorry for the inconvenience.

**Comment by catavallejos** [comment]
Thanks. Documentation works well now
